name: nats-server
version: "0.9.4"
summary: "High-Performance server for NATS"
description: "High-Performance server for NATS, the cloud native messaging system"
confinement: strict

apps:
  nats-server:
    command: gnatsd-v0.9.4-linux-amd64/gnatsd
    plugs: [network-bind]

parts:
  gnatsd:
    plugin: dump
    source: https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip
